name: Buildx latest
on:
  push:
    branches: [master]
    paths-ignore:
      - .github/workflows/buildx-release.yml
      - README.md
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      #- name: Dockerhub login
      #  run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u bee --password-stdin 2>&1
      - name: Run Buildx
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x \
            -t mikesplain/tester:latest \
            --push \
            .
